### ISSUE TITLE
FileSync not working in Sublime Text 3 (beta)

### ISSUE THREAD

**Issue by JohnArcher** [bcharbonnier/SublimeFileSync#1]
Hi there,

I installed FileSync via Package Control in Sublime Text 3 (beta), but under "Preferences" -> "FileSync" both entries are greyed out - it is not possible to customize/activate file sync there.

Is there an update planned or is there a workaround to get it started? I used FileSync successfully with Sublime Text 2.

Thanks a lot in advance!

**Comment by sethstone** [comment]
I'm getting the same issue on ST3 and Windows 8.1:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "filesync in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\FileSync.sublime-package", line 28, in run
AttributeError: 'NoneType' object has no attribute 'set'
```

**Comment by mattchatterley** [comment]
Same here on ST3 - started this morning after the monthly reboot of my Mac; presumably something somewhere has updated and killed it :( Will have a go at fixing if I can find 10 mins.

**Comment by sethstone** [comment]
This has been open for 3 years and you can fix it in 10 minutes?

**Comment by romaopedro** [comment]
the only fix I found was to remove package and install again. The settings don't get lost, so it's relatively fast.
